### ISSUE TITLE
[Proposed enhancement] Allow conditional logic

### ISSUE THREAD

**Issue by maxms** [soderlind/icalendar-ninja-forms#3]
Hi again @soderlind,

We are doing event registration and there are single day or multiple day options. Ideally, an ical file would only include the day(s) they registered for so conditional logic would be helpful to associate an ical with a particular option selection.

Thanks for your time! :)

**Comment by soderlind** [comment]
Hi @maxms,  

Not sure what you mean, do you have multiple date fields in your form? Could you please give me a screenshot of the form?

**Comment by maxms** [comment]
We have a multi-day conference where people can choose to come one day or two days. (See attached #1) So, I would want to create an ical action specific to each of these options so that they only receive an ical with the dates they actually registered for. Other NF actions have a "Conditional Logic" section but I don't see that in your plugin's editor (See attached #2). I hope this makes sense. Our form is already live so it's not something needed right now but it seems like it might be useful for others as well.

<img width="475" alt="1" src="https://user-images.githubusercontent.com/6116506/169144907-a5bfd756-69f0-4ab8-8c6e-d672d8787bc3.png">
<img width="848" alt="2" src="https://user-images.githubusercontent.com/6116506/169144911-d08456c7-7551-4dc0-81d8-bd8cd6b3a9a6.png">

**Comment by maxms** [comment]
That's fantastic! Thanks for your time on this great plugin!

**Comment by soderlind** [comment]
@maxms thank you for the donation :)
